from .base import BaseWeightedLoss
from .cross_entropy_loss import CrossEntropyLoss
from .Inter_Affinitive_Contrastive_Loss import Inter_Affinitive_Contrastive_Loss
from .Intra_Affinitive_Contrastive_Loss import Intra_Affinitive_Contrastive_Loss